[workspace]
members = ["stereokit-macros"]

[package]
name = "stereokit-rust"
version = "0.4.0-alpha.25"
resolver = "2"
edition = "2024"
#rust-version = "1.94"
description = "High-Level Rust bindings around the StereoKitC library for XR"
#homepage = "https://stereokit.net/"
keywords = ["stereokit", "VR", "sys", "MR", "OpenXR"]
license = "MIT"
#license-file = "LICENSE"
links = "StereoKitC"
repository = "https://github.com/mvvvv/StereoKit-rust"
categories = ["graphics", "gui", "rendering::engine", "mathematics", "vr", "xr", "api-bindings"]
include = [
  "Cargo.toml",
  "build.rs",
  "src/*",
  "StereoKit/cmake",
  "StereoKit/tools/include",
  "StereoKit/StereoKitC",
  "StereoKit/CMakeLists.txt",
  "README.md",
  "LICENSE"
]
readme = "README_short.md"

[features]
dynamic-openxr = [] # Add openxr_loader.so in Android APK
build-dynamic-openxr = [ "dynamic-openxr",] # Build openxr_loader from Khronos OpenXR project
no-event-loop = []    # Disable the framework (event loop, steppers, tools)
force-local-deps = []
with_glam = ["dep:glam"]
skc-in-dll = [] # Create and use StereoKitC as a DLL when building for windows (MSVC & GNU)
test-xr-mode = [] # Replace AppMode::Offscreen with AppMode::XR in test macros
profile = [] # Enable profiling in StereoKitC using tracy

[lib]
crate-type = ["lib", "cdylib"]

[[bin]]
name = "cargo-compile_sks"

[[bin]]
name = "cargo-new_sk_rs_project"

[[bin]]
name = "cargo-build_sk_rs"

[build-dependencies]
cmake = "0.1.58"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
thiserror = "2.0"
bitflags = "2.13"
glam = { version = "0.33", optional = true }
openxr-sys = "0.13"
#stereokit-macros = { path = "./stereokit-macros", version = "0.6" }
stereokit-macros = "0.6"

[target.'cfg(target_os = "android")'.dependencies]
log = "0.4"
android_logger = "0.15"
android-activity = { version = "0.6", features = [ "native-activity" ] }
ndk = { version = "0.9.0", features = ["all"] }
ndk-sys = "0.6"
jni = "0.22"

[[example]]
#---For PC only (vscode launcher)
name = "main_pc"
crate-type = ["bin"]

[[example]]
#---For PC only (vscode launcher)
name = "manual"
crate-type = ["bin"]
required-features = ["no-event-loop"]

[[example]]
#---For All using cargo command
name = "main"
crate-type = ["cdylib"]

[[test]]
name = "main_tests"
path = "tests/main_tests.rs"
harness = false

